{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "altiora.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "altiora.name" . }}
  policyTypes:
  - Ingress
  ingress:
{{ toYaml .Values.networkPolicy.ingress | indent 4 }}
{{- end }}