replicaCount: 3
resources:
  requests: { cpu: "500m", memory: "8Gi" }
  limits:   { cpu: "2",   memory: "16Gi" }

# HPA
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 80

# PDB
pdb:
  enabled: true
  minAvailable: 2

# NetworkPolicy
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels: { name: ingress-nginx }
      ports:
      - protocol: TCP
        port: 8000